/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/llm-configs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Llm Configs */
        get: operations["get_llm_configs_api_llm_configs_get"];
        put?: never;
        /** Create Llm Config Endpoint */
        post: operations["create_llm_config_endpoint_api_llm_configs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/llm-configs/{config_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Llm Config Endpoint */
        put: operations["update_llm_config_endpoint_api_llm_configs__config_id__put"];
        post?: never;
        /** Delete Llm Config Endpoint */
        delete: operations["delete_llm_config_endpoint_api_llm_configs__config_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/llm-configs/{config_id}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Activate Llm Config Endpoint */
        post: operations["activate_llm_config_endpoint_api_llm_configs__config_id__activate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/llm-configs/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Test Llm Config Endpoint */
        post: operations["test_llm_config_endpoint_api_llm_configs_test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/graph-configs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Graph Configs */
        get: operations["get_graph_configs_api_graph_configs_get"];
        put?: never;
        /** Create Graph Config Endpoint */
        post: operations["create_graph_config_endpoint_api_graph_configs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/graph-configs/{config_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Graph Config Endpoint */
        put: operations["update_graph_config_endpoint_api_graph_configs__config_id__put"];
        post?: never;
        /** Delete Graph Config Endpoint */
        delete: operations["delete_graph_config_endpoint_api_graph_configs__config_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/graph-configs/{config_id}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Activate Graph Config Endpoint */
        post: operations["activate_graph_config_endpoint_api_graph_configs__config_id__activate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Conversations */
        get: operations["get_conversations_api_conversations_get"];
        put?: never;
        /** Create Conversation Endpoint */
        post: operations["create_conversation_endpoint_api_conversations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{conversation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Conversation Endpoint */
        get: operations["get_conversation_endpoint_api_conversations__conversation_id__get"];
        put?: never;
        post?: never;
        /** Delete Conversation Endpoint */
        delete: operations["delete_conversation_endpoint_api_conversations__conversation_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat Stream */
        post: operations["chat_stream_api_chat_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat */
        post: operations["chat_api_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ChatMessage */
        ChatMessage: {
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant" | "system";
            /** Content */
            content: string;
        };
        /** ChatRequest */
        ChatRequest: {
            /** Message */
            message?: string | null;
            /** Messages */
            messages?: components["schemas"]["ChatMessage"][];
        };
        /** ChatResponse */
        ChatResponse: {
            /** Response */
            response: string;
            message: components["schemas"]["ChatMessage"];
        };
        /** ChatStreamRequest */
        ChatStreamRequest: {
            /** Conversation Id */
            conversation_id: number;
            /** Message */
            message: string;
        };
        /** ConversationDetailResponse */
        ConversationDetailResponse: {
            conversation: components["schemas"]["ConversationRecord"];
            /** Messages */
            messages: components["schemas"]["ConversationMessageRecord"][];
        };
        /** ConversationListResponse */
        ConversationListResponse: {
            /** Items */
            items: components["schemas"]["ConversationSummary"][];
        };
        /** ConversationMessageRecord */
        ConversationMessageRecord: {
            /** Id */
            id: number;
            /** Conversation Id */
            conversation_id: number;
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant" | "system";
            /** Content */
            content: string;
            /** Created At */
            created_at: string;
        };
        /** ConversationRecord */
        ConversationRecord: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
        };
        /** ConversationSummary */
        ConversationSummary: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
            /**
             * Preview
             * @default
             */
            preview: string;
            /**
             * Message Count
             * @default 0
             */
            message_count: number;
        };
        /** GraphConfigCreateRequest */
        GraphConfigCreateRequest: {
            /** Name */
            name: string;
            graph_type: components["schemas"]["GraphType"];
            /**
             * System Prompt
             * @default
             */
            system_prompt: string;
            /**
             * Analyzer Prompt
             * @default
             */
            analyzer_prompt: string;
            /**
             * Deconstructor Prompt
             * @default
             */
            deconstructor_prompt: string;
        };
        /** GraphConfigListResponse */
        GraphConfigListResponse: {
            /** Items */
            items: components["schemas"]["GraphConfigRecord"][];
            /** Active Config Id */
            active_config_id?: number | null;
        };
        /** GraphConfigRecord */
        GraphConfigRecord: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            graph_type: components["schemas"]["GraphType"];
            /** System Prompt */
            system_prompt: string;
            /**
             * Analyzer Prompt
             * @default
             */
            analyzer_prompt: string;
            /**
             * Deconstructor Prompt
             * @default
             */
            deconstructor_prompt: string;
            /** Is Active */
            is_active: boolean;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
        };
        /** GraphConfigUpdateRequest */
        GraphConfigUpdateRequest: {
            /** Name */
            name: string;
            graph_type: components["schemas"]["GraphType"];
            /**
             * System Prompt
             * @default
             */
            system_prompt: string;
            /**
             * Analyzer Prompt
             * @default
             */
            analyzer_prompt: string;
            /**
             * Deconstructor Prompt
             * @default
             */
            deconstructor_prompt: string;
        };
        /**
         * GraphType
         * @enum {string}
         */
        GraphType: "simple_chat" | "summary_analysis";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Configured */
            configured: boolean;
            /** Source */
            source?: string | null;
            /** Config Name */
            config_name?: string | null;
            /** Model */
            model?: string | null;
            /** Max Retries */
            max_retries?: number | null;
        };
        /** LLMConfigCreateRequest */
        LLMConfigCreateRequest: {
            /** Name */
            name: string;
            /** Api Key */
            api_key: string;
            /** Model */
            model: string;
            /** Base Url */
            base_url?: string | null;
            /**
             * Temperature
             * @default 0.2
             */
            temperature: number;
            /**
             * Max Retries
             * @default 2
             */
            max_retries: number;
        };
        /** LLMConfigListResponse */
        LLMConfigListResponse: {
            /** Items */
            items: components["schemas"]["LLMConfigRecord"][];
            /** Active Config Id */
            active_config_id?: number | null;
        };
        /** LLMConfigRecord */
        LLMConfigRecord: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Api Key Masked */
            api_key_masked: string;
            /** Model */
            model: string;
            /** Base Url */
            base_url?: string | null;
            /** Temperature */
            temperature: number;
            /** Max Retries */
            max_retries: number;
            /** Is Active */
            is_active: boolean;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
        };
        /** LLMConfigTestRequest */
        LLMConfigTestRequest: {
            /** Api Key */
            api_key: string;
            /** Model */
            model: string;
            /** Base Url */
            base_url?: string | null;
            /**
             * Temperature
             * @default 0.2
             */
            temperature: number;
            /**
             * Max Retries
             * @default 2
             */
            max_retries: number;
        };
        /** LLMConfigTestResponse */
        LLMConfigTestResponse: {
            /** Success */
            success: boolean;
            /** Message */
            message: string;
            /** Response Preview */
            response_preview?: string | null;
        };
        /** LLMConfigUpdateRequest */
        LLMConfigUpdateRequest: {
            /** Name */
            name: string;
            /** Api Key */
            api_key?: string | null;
            /** Model */
            model: string;
            /** Base Url */
            base_url?: string | null;
            /**
             * Temperature
             * @default 0.2
             */
            temperature: number;
            /**
             * Max Retries
             * @default 2
             */
            max_retries: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    get_llm_configs_api_llm_configs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LLMConfigListResponse"];
                };
            };
        };
    };
    create_llm_config_endpoint_api_llm_configs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LLMConfigCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LLMConfigRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_llm_config_endpoint_api_llm_configs__config_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                config_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LLMConfigUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LLMConfigRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_llm_config_endpoint_api_llm_configs__config_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                config_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    activate_llm_config_endpoint_api_llm_configs__config_id__activate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                config_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LLMConfigRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_llm_config_endpoint_api_llm_configs_test_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LLMConfigTestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LLMConfigTestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_graph_configs_api_graph_configs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphConfigListResponse"];
                };
            };
        };
    };
    create_graph_config_endpoint_api_graph_configs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GraphConfigCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphConfigRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_graph_config_endpoint_api_graph_configs__config_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                config_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GraphConfigUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphConfigRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_graph_config_endpoint_api_graph_configs__config_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                config_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    activate_graph_config_endpoint_api_graph_configs__config_id__activate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                config_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphConfigRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_conversations_api_conversations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationListResponse"];
                };
            };
        };
    };
    create_conversation_endpoint_api_conversations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationRecord"];
                };
            };
        };
    };
    get_conversation_endpoint_api_conversations__conversation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_conversation_endpoint_api_conversations__conversation_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_stream_api_chat_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatStreamRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_api_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
