/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Auth Session */
        get: operations["get_auth_session_api_auth_session_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Ai Logs */
        get: operations["get_ai_logs_api_ai_logs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/liked-cards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Liked Cards */
        get: operations["get_liked_cards_api_liked_cards_get"];
        put?: never;
        /** Create Liked Card Endpoint */
        post: operations["create_liked_card_endpoint_api_liked_cards_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/liked-cards/{liked_card_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Liked Card Endpoint */
        delete: operations["delete_liked_card_endpoint_api_liked_cards__liked_card_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/llm-configs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Llm Configs */
        get: operations["get_llm_configs_api_llm_configs_get"];
        put?: never;
        /** Create Llm Config Endpoint */
        post: operations["create_llm_config_endpoint_api_llm_configs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/llm-configs/{config_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Llm Config Endpoint */
        put: operations["update_llm_config_endpoint_api_llm_configs__config_id__put"];
        post?: never;
        /** Delete Llm Config Endpoint */
        delete: operations["delete_llm_config_endpoint_api_llm_configs__config_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/llm-configs/{config_id}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Activate Llm Config Endpoint */
        post: operations["activate_llm_config_endpoint_api_llm_configs__config_id__activate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/llm-configs/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Test Llm Config Endpoint */
        post: operations["test_llm_config_endpoint_api_llm_configs_test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/graph-configs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Graph Configs */
        get: operations["get_graph_configs_api_graph_configs_get"];
        put?: never;
        /** Create Graph Config Endpoint */
        post: operations["create_graph_config_endpoint_api_graph_configs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/graph-configs/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview Graph Config Endpoint */
        post: operations["preview_graph_config_endpoint_api_graph_configs_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/graph-configs/{config_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Graph Config Endpoint */
        put: operations["update_graph_config_endpoint_api_graph_configs__config_id__put"];
        post?: never;
        /** Delete Graph Config Endpoint */
        delete: operations["delete_graph_config_endpoint_api_graph_configs__config_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/graph-configs/{config_id}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Activate Graph Config Endpoint */
        post: operations["activate_graph_config_endpoint_api_graph_configs__config_id__activate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Conversations */
        get: operations["get_conversations_api_conversations_get"];
        put?: never;
        /** Create Conversation Endpoint */
        post: operations["create_conversation_endpoint_api_conversations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{conversation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Conversation Endpoint */
        get: operations["get_conversation_endpoint_api_conversations__conversation_id__get"];
        put?: never;
        post?: never;
        /** Delete Conversation Endpoint */
        delete: operations["delete_conversation_endpoint_api_conversations__conversation_id__delete"];
        options?: never;
        head?: never;
        /** Update Conversation Endpoint */
        patch: operations["update_conversation_endpoint_api_conversations__conversation_id__patch"];
        trace?: never;
    };
    "/api/chat/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat Stream */
        post: operations["chat_stream_api_chat_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat */
        post: operations["chat_api_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AILogListResponse */
        AILogListResponse: {
            /** Items */
            items: components["schemas"]["AILogRecord"][];
        };
        /** AILogMessage */
        AILogMessage: {
            /** Role */
            role: string;
            /** Content */
            content: string;
        };
        /** AILogRecord */
        AILogRecord: {
            /** Id */
            id: number;
            /** Request Id */
            request_id: string;
            /** Conversation Id */
            conversation_id?: number | null;
            /** Conversation Title */
            conversation_title?: string | null;
            /** Graph Config Id */
            graph_config_id?: number | null;
            /** Graph Config Name */
            graph_config_name?: string | null;
            /** Node Name */
            node_name?: string | null;
            /** Node Label */
            node_label?: string | null;
            /** Operation */
            operation?: string | null;
            /** Llm Source */
            llm_source?: string | null;
            /** Llm Config Name */
            llm_config_name?: string | null;
            /** Model */
            model?: string | null;
            status: components["schemas"]["AILogStatus"];
            /** Attempt Count */
            attempt_count: number;
            /** Duration Ms */
            duration_ms: number;
            /** Input Messages */
            input_messages?: components["schemas"]["AILogMessage"][];
            /** Response Text */
            response_text?: string | null;
            /** Error Message */
            error_message?: string | null;
            /** Created At */
            created_at: string;
        };
        /**
         * AILogStatus
         * @enum {string}
         */
        AILogStatus: "success" | "error";
        /** AuthLoginRequest */
        AuthLoginRequest: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** AuthSessionResponse */
        AuthSessionResponse: {
            /** Authenticated */
            authenticated: boolean;
            /** Username */
            username?: string | null;
        };
        /** ChatMessage */
        ChatMessage: {
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant" | "system";
            /** Content */
            content: string;
        };
        /** ChatRequest */
        ChatRequest: {
            /** Message */
            message?: string | null;
            /** Messages */
            messages?: components["schemas"]["ChatMessage"][];
        };
        /** ChatResponse */
        ChatResponse: {
            /** Response */
            response: string;
            message: components["schemas"]["ChatMessage"];
        };
        /** ChatStreamRequest */
        ChatStreamRequest: {
            /** Conversation Id */
            conversation_id: number;
            /** Message */
            message: string;
        };
        /** ConversationCreateRequest */
        ConversationCreateRequest: {
            /**
             * Title
             * @default New chat
             */
            title: string;
            /** Graph Config Id */
            graph_config_id?: number | null;
        };
        /** ConversationDetailResponse */
        ConversationDetailResponse: {
            conversation: components["schemas"]["ConversationRecord"];
            /** Messages */
            messages: components["schemas"]["ConversationMessageRecord"][];
        };
        /** ConversationListResponse */
        ConversationListResponse: {
            /** Items */
            items: components["schemas"]["ConversationSummary"][];
        };
        /** ConversationMessageRecord */
        ConversationMessageRecord: {
            /** Id */
            id: number;
            /** Conversation Id */
            conversation_id: number;
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant" | "system";
            /** Content */
            content: string;
            /** Node */
            node?: string | null;
            /** Node Label */
            node_label?: string | null;
            /** State Patch */
            state_patch?: {
                [key: string]: string;
            };
            /** Created At */
            created_at: string;
        };
        /** ConversationRecord */
        ConversationRecord: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Graph Config Id */
            graph_config_id?: number | null;
            /** Graph Config Name */
            graph_config_name?: string | null;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
        };
        /** ConversationSummary */
        ConversationSummary: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Graph Config Id */
            graph_config_id?: number | null;
            /** Graph Config Name */
            graph_config_name?: string | null;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
            /**
             * Preview
             * @default
             */
            preview: string;
            /**
             * Message Count
             * @default 0
             */
            message_count: number;
        };
        /** ConversationUpdateRequest */
        ConversationUpdateRequest: {
            /** Title */
            title?: string | null;
            /** Graph Config Id */
            graph_config_id?: number | null;
        };
        /** GraphConfigCreateRequest */
        GraphConfigCreateRequest: {
            /** Name */
            name: string;
            graph_type: components["schemas"]["GraphType"];
            /**
             * System Prompt
             * @default
             */
            system_prompt: string;
            /**
             * Analyzer Prompt
             * @default
             */
            analyzer_prompt: string;
            /**
             * Deconstructor Prompt
             * @default
             */
            deconstructor_prompt: string;
            /** Prompt Values */
            prompt_values?: {
                [key: string]: string;
            };
        };
        /** GraphConfigListResponse */
        GraphConfigListResponse: {
            /** Items */
            items: components["schemas"]["GraphConfigRecord"][];
            /** Active Config Id */
            active_config_id?: number | null;
        };
        /** GraphConfigRecord */
        GraphConfigRecord: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            graph_type: components["schemas"]["GraphType"];
            /** System Prompt */
            system_prompt: string;
            /**
             * Analyzer Prompt
             * @default
             */
            analyzer_prompt: string;
            /**
             * Deconstructor Prompt
             * @default
             */
            deconstructor_prompt: string;
            /** Prompt Values */
            prompt_values?: {
                [key: string]: string;
            };
            /** Is Active */
            is_active: boolean;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
        };
        /** GraphConfigUpdateRequest */
        GraphConfigUpdateRequest: {
            /** Name */
            name: string;
            graph_type: components["schemas"]["GraphType"];
            /**
             * System Prompt
             * @default
             */
            system_prompt: string;
            /**
             * Analyzer Prompt
             * @default
             */
            analyzer_prompt: string;
            /**
             * Deconstructor Prompt
             * @default
             */
            deconstructor_prompt: string;
            /** Prompt Values */
            prompt_values?: {
                [key: string]: string;
            };
        };
        /** GraphNodePromptPreview */
        GraphNodePromptPreview: {
            /** Node */
            node: string;
            /** Node Label */
            node_label: string;
            /** Purpose */
            purpose: string;
            /** Reads */
            reads?: string[];
            /** Writes */
            writes?: string[];
            /** Prompt Source */
            prompt_source: string;
            /** Prompt Preview */
            prompt_preview: string;
        };
        /** GraphPromptFieldPreview */
        GraphPromptFieldPreview: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Description */
            description: string;
            /** Placeholder */
            placeholder: string;
        };
        /** GraphPromptPreviewRequest */
        GraphPromptPreviewRequest: {
            graph_type: components["schemas"]["GraphType"];
            /**
             * System Prompt
             * @default
             */
            system_prompt: string;
            /**
             * Analyzer Prompt
             * @default
             */
            analyzer_prompt: string;
            /**
             * Deconstructor Prompt
             * @default
             */
            deconstructor_prompt: string;
            /** Prompt Values */
            prompt_values?: {
                [key: string]: string;
            };
        };
        /** GraphPromptPreviewResponse */
        GraphPromptPreviewResponse: {
            /** Items */
            items: components["schemas"]["GraphNodePromptPreview"][];
            /** State Slots */
            state_slots?: components["schemas"]["GraphStateSlotPreview"][];
            /** Prompt Fields */
            prompt_fields?: components["schemas"]["GraphPromptFieldPreview"][];
        };
        /** GraphStateSlotPreview */
        GraphStateSlotPreview: {
            /** Name */
            name: string;
            /** Label */
            label: string;
            /** Description */
            description: string;
            /** Kind */
            kind: string;
            /** Written By */
            written_by?: string[];
            /** Read By */
            read_by?: string[];
        };
        /**
         * GraphType
         * @enum {string}
         */
        GraphType: "simple_chat" | "summary_analysis" | "viral_tweet" | "article_value";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Configured */
            configured: boolean;
            /** Source */
            source?: string | null;
            /** Config Name */
            config_name?: string | null;
            /** Model */
            model?: string | null;
            /** Max Retries */
            max_retries?: number | null;
        };
        /** LLMConfigCreateRequest */
        LLMConfigCreateRequest: {
            /** Name */
            name: string;
            /** Api Key */
            api_key: string;
            /** Model */
            model: string;
            /** Base Url */
            base_url?: string | null;
            /**
             * Temperature
             * @default 0.2
             */
            temperature: number;
            /**
             * Max Retries
             * @default 2
             */
            max_retries: number;
        };
        /** LLMConfigListResponse */
        LLMConfigListResponse: {
            /** Items */
            items: components["schemas"]["LLMConfigRecord"][];
            /** Active Config Id */
            active_config_id?: number | null;
        };
        /** LLMConfigRecord */
        LLMConfigRecord: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Api Key Masked */
            api_key_masked: string;
            /** Model */
            model: string;
            /** Base Url */
            base_url?: string | null;
            /** Temperature */
            temperature: number;
            /** Max Retries */
            max_retries: number;
            /** Is Active */
            is_active: boolean;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
        };
        /** LLMConfigTestRequest */
        LLMConfigTestRequest: {
            /** Api Key */
            api_key: string;
            /** Model */
            model: string;
            /** Base Url */
            base_url?: string | null;
            /**
             * Temperature
             * @default 0.2
             */
            temperature: number;
            /**
             * Max Retries
             * @default 2
             */
            max_retries: number;
        };
        /** LLMConfigTestResponse */
        LLMConfigTestResponse: {
            /** Success */
            success: boolean;
            /** Message */
            message: string;
            /** Response Preview */
            response_preview?: string | null;
        };
        /** LLMConfigUpdateRequest */
        LLMConfigUpdateRequest: {
            /** Name */
            name: string;
            /** Api Key */
            api_key?: string | null;
            /** Model */
            model: string;
            /** Base Url */
            base_url?: string | null;
            /**
             * Temperature
             * @default 0.2
             */
            temperature: number;
            /**
             * Max Retries
             * @default 2
             */
            max_retries: number;
        };
        /** LikedCardCreateRequest */
        LikedCardCreateRequest: {
            /** Conversation Id */
            conversation_id: number;
            /** Source Message Id */
            source_message_id: number;
            /** Card Index */
            card_index: number;
            /** Route Label */
            route_label?: string | null;
            /** Title */
            title: string;
            /** Content */
            content: string;
        };
        /** LikedCardListResponse */
        LikedCardListResponse: {
            /** Items */
            items: components["schemas"]["LikedCardRecord"][];
        };
        /** LikedCardRecord */
        LikedCardRecord: {
            /** Id */
            id: number;
            /** Conversation Id */
            conversation_id: number;
            /** Conversation Title */
            conversation_title?: string | null;
            /** Source Message Id */
            source_message_id: number;
            /** Card Index */
            card_index: number;
            /** Route Label */
            route_label?: string | null;
            /** Title */
            title: string;
            /** Content */
            content: string;
            /** Created At */
            created_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    get_auth_session_api_auth_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSessionResponse"];
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthLoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSessionResponse"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    get_ai_logs_api_ai_logs_get: {
        parameters: {
            query?: {
                conversation_id?: number | null;
                request_id?: string | null;
                status?: components["schemas"]["AILogStatus"] | null;
                node_name?: string | null;
                graph_config_id?: number | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AILogListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_liked_cards_api_liked_cards_get: {
        parameters: {
            query?: {
                conversation_id?: number | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LikedCardListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_liked_card_endpoint_api_liked_cards_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LikedCardCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LikedCardRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_liked_card_endpoint_api_liked_cards__liked_card_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                liked_card_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_llm_configs_api_llm_configs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LLMConfigListResponse"];
                };
            };
        };
    };
    create_llm_config_endpoint_api_llm_configs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LLMConfigCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LLMConfigRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_llm_config_endpoint_api_llm_configs__config_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                config_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LLMConfigUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LLMConfigRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_llm_config_endpoint_api_llm_configs__config_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                config_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    activate_llm_config_endpoint_api_llm_configs__config_id__activate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                config_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LLMConfigRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_llm_config_endpoint_api_llm_configs_test_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LLMConfigTestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LLMConfigTestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_graph_configs_api_graph_configs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphConfigListResponse"];
                };
            };
        };
    };
    create_graph_config_endpoint_api_graph_configs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GraphConfigCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphConfigRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_graph_config_endpoint_api_graph_configs_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GraphPromptPreviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphPromptPreviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_graph_config_endpoint_api_graph_configs__config_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                config_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GraphConfigUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphConfigRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_graph_config_endpoint_api_graph_configs__config_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                config_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    activate_graph_config_endpoint_api_graph_configs__config_id__activate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                config_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphConfigRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_conversations_api_conversations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationListResponse"];
                };
            };
        };
    };
    create_conversation_endpoint_api_conversations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ConversationCreateRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_conversation_endpoint_api_conversations__conversation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_conversation_endpoint_api_conversations__conversation_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_conversation_endpoint_api_conversations__conversation_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConversationUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_stream_api_chat_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatStreamRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_api_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
